name: 构建应用程序/Build

on:
  push:
    branches: [ "python-windows" ]
  pull_request:
    branches: [ "python-windows" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2025
    steps:
      - name: 正在进入分支/Checkout
        uses: actions/checkout@v4
      - name: 安装python环境/Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'
      - name: 安装必要的库/Install requirements and installer
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
      - name: 构建应用程序/Run pyinstaller
        run: |
          python -m PyInstaller .\build.spec --noconfirm
      - name: 上传应用程序/Upload the .exe file
        uses: actions/upload-artifact@v3.0
        with:
          name: JimGrasscutterServerLauncher.exe
          path: dist/JimGrasscutterServerLauncher.exe
      - name: 获取最新的Tag/Get latest tag
        id: get_tag
        run: |
          tag=$(git describe --tags --abbrev=0 2>/dev/null || echo "V0.0.0")
          echo "Last tag: $tag"
          echo "tag=$tag" >> $GITHUB_OUTPUT
      - name: 生成版本号/Calculate version
        id: version
        run: |
          last_tag="${{ steps.get_tag.outputs.tag }}"
          run_number=${{ github.run_number }}
          version_no_v=${last_tag#V}
          IFS='.' read -r major minor patch <<< "$version_no_v"
          event_name="${{ github.event_name }}"
          if [ "$event_name" = "push" ]; then
            minor=$((minor + 1))
            if [ $minor -gt 9 ]; then
             minor=0
             major=$((major + 1))
            fi
          elif [ "$event_name" = "pull_request" ]; then
            major=$((major + 1))
         else
            echo "手动触发的构建，拒绝生成版本号，不创建release和tag/Manual trigger-skipping version/tag creation"
            echo "skip_release=true" >> $GITHUB_OUTPUT
            exit 0
         fi
          new_tag="V$major.$minor.$run_number"
          echo "新的版本！/New tag: $new_tag"
          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT
      - name: 创建新的Tag/Create tag
        if: steps.version.outputs.skip_release != 'true'
        run: |
         git config user.name github-actions
         git config user.email github-actions@github.com
         git tag ${{ steps.version.outputs.new_tag }}
         git push origin ${{ steps.version.outputs.new_tag }}
      - name: 生成更改日志/Generate Changelog
        id: changelog
        run: |
          last_tag=${{ steps.get_tag.outputs.tag }}
          log=$(git log "$last_tag"..HEAD --pretty=format:"- %s")
          if [ -z "$log" ]; then
            log="没有发现更改/No significant changes."
          fi
          echo "$log" > changelog.txt
          echo "changelog<<EOF" >> $GITHUB_OUTPUT
          echo "$log" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      - name: 创建发行版/create release
        if: steps.version.outputs.skip_release != 'true'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.new_tag }}
          release_name: Release ${{ steps.version.outputs.new_tag }}
          body: |
            ## 新更改/Changelog
            ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false
      - name: 上传发行版应用程序/Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
           upload_url: ${{ steps.create_release.outputs.upload_url }}
           asset_path: dist/JimGrasscutterServerLauncher.exe
           asset_name: JimGrasscutterServerLauncher.exe
           asset_content_type: application/octet-stream